server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #\u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql\u9A71\u52A8\u5305
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.daxiang.springcloud.entities       #\u6240\u6709Entity\u522B\u540D\u7C7B\u6240\u5728\u5305
