server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动类
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.daxiang.springcloud.entities

eureka:
  client:
    #向eureka server注册.表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #抓取已有的注册信息.是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
    #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #eureka服务端在收到最后一次心跳后等待的时间上限,单位秒默认90,超时将提出服务
    #lease-expiration-duration-in-seconds: 10
    #eureka客户端向服务器发送心跳的时间间隔,单位秒 默认值30
    #lease-renewal-interval-in-seconds: 1